name: chemiplay
description: chemiplay

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  # Firebase
  firebase_core:
  firebase_analytics:
  firebase_auth:
  cloud_firestore:
  cloud_functions:
  firebase_database:
  firebase_storage:
  cloud_firestore_odm:
  logger: ^1.3.0
  get_it: ^7.2.0
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.0
  flutter_svg: ^2.0.5
  go_router: ^6.5.7
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.1
  # sendbird
  sendbird_sdk: ^3.1.15
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/games/
    - assets/data/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
