name: chemiplay
description: chemiplay

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  # Firebase
  firebase_core:
  firebase_analytics:
  firebase_auth:
  cloud_firestore:
  cloud_functions:
  firebase_database:
  firebase_storage:
  cloud_firestore_odm:
  logger: ^1.3.0
  get_it: ^7.2.0
  google_sign_in: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
